Repository taba7-algorivew/backend, pull requests merged in 2025-02, with the labels that each got.

#80 Chore: Add Dockerfile for containerization
  .dockerignore
  Dockerfile
Labels: Production

#84 Refactor: get_info_img process
  review/ai_module.py
  review/input_source_precessing.py
Labels: bugfix, [GENAI] image_to_text

#85 Refactor: Chatbot service
  review/ai_module.py
Labels: [Open AI] generate_chatbot, Enhance

#86 lines prompt 성능 향상
  review/ai_module.py
Labels: [Open AI] generate_review, [Open AI] generate_re_review

#89 Fix(get_info_img): Improve image processing flow
  review/input_source_precessing.py
Labels: bugfix, [GENAI] image_to_text

#95 Feat(CI): add workflow for Docker image build and ECR push with commit SHA tags
  .github/workflows/ci-ecr.yml
Labels: Enhance, Production
